### ISSUE TITLE
Add DNSSECOperationsOnly OT&E-only test plan

### ISSUE THREAD

**Issue by gbicann** [icann/rst-test-specs#5]
With the exception of [DNSSEC Operations](https://icann.github.io/rst-test-specs/rst-test-specs.html#Test-Suite-DNSSECOperations), every other test suite has a corresponding test plan, which is only available in OT&E, that allows that specific test suite to be tested.

```yaml
DNSSECOperationsOnly:
  Name: DNSSEC Operations (OT&E Only)
  Description: |
    This test plan allows an RSP to request testing of a single test suite,
    specifically the `DNSSECOperations` suite.
  Test-Suites:
    - DNSSECOperations
  OTE-Only: true
```
